//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDigits.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckDigits.Net.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Bankers Association Routing Transit Number algorithm with weights 3, 7 and 1.
        /// </summary>
        internal static string AbaRtnAlgorithmDescription {
            get {
                return ResourceManager.GetString("AbaRtnAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABA RTN.
        /// </summary>
        internal static string AbaRtnAlgorithmName {
            get {
                return ResourceManager.GetString("AbaRtnAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm description may not be null, String.Empty or all whitespace characters.
        /// </summary>
        internal static string AlgorithmDescriptionIsEmptyMessage {
            get {
                return ResourceManager.GetString("AlgorithmDescriptionIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm name may not be null, String.Empty or all whitespace characters.
        /// </summary>
        internal static string AlgorithmNameIsEmptyMessage {
            get {
                return ResourceManager.GetString("AlgorithmNameIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation of ISO/IEC 7064 MOD 97-10 algorithm with alphabetic characters (A-Z) mapped to integers (10-35).
        /// </summary>
        internal static string AlphanumericMod97_10AlgorithmDescription {
            get {
                return ResourceManager.GetString("AlphanumericMod97_10AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphanumericMod97_10.
        /// </summary>
        internal static string AlphanumericMod97_10AlgorithmName {
            get {
                return ResourceManager.GetString("AlphanumericMod97_10AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSIP Algorithm.
        /// </summary>
        internal static string CusipAlgorithmDescription {
            get {
                return ResourceManager.GetString("CusipAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSIP.
        /// </summary>
        internal static string CusipAlgorithmName {
            get {
                return ResourceManager.GetString("CusipAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damm&apos;s quasigroup algorithm.
        /// </summary>
        internal static string DammAlgorithmDescription {
            get {
                return ResourceManager.GetString("DammAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damm.
        /// </summary>
        internal static string DammAlgorithmName {
            get {
                return ResourceManager.GetString("DammAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIGI Algorithm.
        /// </summary>
        internal static string FigiAlgorithmDescription {
            get {
                return ResourceManager.GetString("FigiAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIGI.
        /// </summary>
        internal static string FigiAlgorithmName {
            get {
                return ResourceManager.GetString("FigiAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check digit value is out of range for the character domain.
        /// </summary>
        internal static string GetCheckCharacterValueOutOfRangeMessage {
            get {
                return ResourceManager.GetString("GetCheckCharacterValueOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN algorithm - ISO/IEC 7064 MOD 97-10 algorithm with alphabetic characters (A-Z) mapped to integers (10-35).
        /// </summary>
        internal static string IbanAlgorithmDescription {
            get {
                return ResourceManager.GetString("IbanAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN (International Bank Account Number).
        /// </summary>
        internal static string IbanAlgorithmName {
            get {
                return ResourceManager.GetString("IbanAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICAO 9303 algorithm - modulus 10 algorithm used by ICAO (Internation Civil Aviation Organization) machine readable travel documents.
        /// </summary>
        internal static string Icao9303AlgorithmDescription {
            get {
                return ResourceManager.GetString("Icao9303AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icao9303.
        /// </summary>
        internal static string Icao9303AlgorithmName {
            get {
                return ResourceManager.GetString("Icao9303AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Algorithm for Machine Readable Visas.
        /// </summary>
        internal static string Icao9303MachineReadableVisaAlgorithmDescription {
            get {
                return ResourceManager.GetString("Icao9303MachineReadableVisaAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Machine Readable Visa.
        /// </summary>
        internal static string Icao9303MachineReadableVisaAlgorithmName {
            get {
                return ResourceManager.GetString("Icao9303MachineReadableVisaAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Algorithm for Machine Readable Documents Size TD1.
        /// </summary>
        internal static string Icao9303SizeTD1AlgorithmDescription {
            get {
                return ResourceManager.GetString("Icao9303SizeTD1AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Document Size TD1.
        /// </summary>
        internal static string Icao9303SizeTD1AlgorithmName {
            get {
                return ResourceManager.GetString("Icao9303SizeTD1AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Algorithm for Machine Readable Documents Size TD2.
        /// </summary>
        internal static string Icao9303SizeTD2AlgorithmDescription {
            get {
                return ResourceManager.GetString("Icao9303SizeTD2AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Document Size TD2.
        /// </summary>
        internal static string Icao9303SizeTD2AlgorithmName {
            get {
                return ResourceManager.GetString("Icao9303SizeTD2AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Algorithm for Machine Readable Documents Size TD3.
        /// </summary>
        internal static string Icao9303SizeTD3AlgorithmDescription {
            get {
                return ResourceManager.GetString("Icao9303SizeTD3AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IACO 9303 Document Size TD3 .
        /// </summary>
        internal static string Icao9303SizeTD3AlgorithmName {
            get {
                return ResourceManager.GetString("Icao9303SizeTD3AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation of ISO/IEC 7064 MOD 37,36 for ISAN values formatted as human readable strings.
        /// </summary>
        internal static string IsanAlgorithmDescription {
            get {
                return ResourceManager.GetString("IsanAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISAN (International Standard Audiovisual Number).
        /// </summary>
        internal static string IsanAlgorithmName {
            get {
                return ResourceManager.GetString("IsanAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation of the Luhn algorithm that supports alphanumeric characters.
        /// </summary>
        internal static string IsinAlgorithmDescription {
            get {
                return ResourceManager.GetString("IsinAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISIN (International Securities Identity Number).
        /// </summary>
        internal static string IsinAlgorithmName {
            get {
                return ResourceManager.GetString("IsinAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 6346 algorithm.
        /// </summary>
        internal static string Iso6346AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso6346AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 6346.
        /// </summary>
        internal static string Iso6346AlgorithmName {
            get {
                return ResourceManager.GetString("Iso6346AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet may not be null.
        /// </summary>
        internal static string Iso7046AlphabetIsNull {
            get {
                return ResourceManager.GetString("Iso7046AlphabetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 hybrid system check digit algorithm with modulus 10.
        /// </summary>
        internal static string Iso7064Mod11_10AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod11_10AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 11,10.
        /// </summary>
        internal static string Iso7064Mod11_10AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod11_10AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 check digit algorithm with modulus 11 and radix 2.
        /// </summary>
        internal static string Iso7064Mod11_2AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod11_2AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 11-2.
        /// </summary>
        internal static string Iso7064Mod11_2AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod11_2AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 check digit algorithm with modulus 1271 and radix 36.
        /// </summary>
        internal static string Iso7064Mod1271_36AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod1271_36AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 1271-36.
        /// </summary>
        internal static string Iso7064Mod1271_36AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod1271_36AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 hybrid system check digit algorithm with modulus 26.
        /// </summary>
        internal static string Iso7064Mod27_26AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod27_26AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 27,26.
        /// </summary>
        internal static string Iso7064Mod27_26AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod27_26AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 check digit algorithm with modulus 37 and radix 2.
        /// </summary>
        internal static string Iso7064Mod37_2AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod37_2AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 37-2.
        /// </summary>
        internal static string Iso7064Mod37_2AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod37_2AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 hybrid system check digit algorithm with modulus 36.
        /// </summary>
        internal static string Iso7064Mod37_36AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod37_36AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 37,36.
        /// </summary>
        internal static string Iso7064Mod37_36AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod37_36AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 check digit algorithm with modulus 661 and radix 26.
        /// </summary>
        internal static string Iso7064Mod661_26AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod661_26AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 661-26.
        /// </summary>
        internal static string Iso7064Mod661_26AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod661_26AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 check digit algorithm with modulus 97 and radix 10.
        /// </summary>
        internal static string Iso7064Mod97_10AlgorithmDescription {
            get {
                return ResourceManager.GetString("Iso7064Mod97_10AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO/IEC 7064 MOD 97-10.
        /// </summary>
        internal static string Iso7064Mod97_10AlgorithmName {
            get {
                return ResourceManager.GetString("Iso7064Mod97_10AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus must be greater than one.
        /// </summary>
        internal static string Iso7064ModulusOutOfRange {
            get {
                return ResourceManager.GetString("Iso7064ModulusOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix must be greater than one.
        /// </summary>
        internal static string Iso7064RadixOutOfRange {
            get {
                return ResourceManager.GetString("Iso7064RadixOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid member of the LineSeparator enumeration (None, Crlf or Lf).
        /// </summary>
        internal static string LineSeparatorInvalidValueMessage {
            get {
                return ResourceManager.GetString("LineSeparatorInvalidValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhn algorithm - modulus 10 algorithm with weight 2 applied to every odd position character.
        /// </summary>
        internal static string LuhnAlgorithmDescription {
            get {
                return ResourceManager.GetString("LuhnAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhn.
        /// </summary>
        internal static string LuhnAlgorithmName {
            get {
                return ResourceManager.GetString("LuhnAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_13 - modulus 10 algorithm with weights 1 and 3.
        /// </summary>
        internal static string Modulus10_13AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus10_13AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_13.
        /// </summary>
        internal static string Modulus10_13AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus10_13AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus 10 algorithm where every character is weighted by its position, starting with weight 1 for the right-most non-check digit character.
        /// </summary>
        internal static string Modulus10_1AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus10_1AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_1.
        /// </summary>
        internal static string Modulus10_1AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus10_1AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus 10 algorithm where every character is weighted by its position, starting with weight 2 for the right-most non-check digit character.
        /// </summary>
        internal static string Modulus10_2AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus10_2AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_2.
        /// </summary>
        internal static string Modulus10_2AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus10_2AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus 11 algorithm where every character is weighted by its position, starting from the right-most character. Generated check digit will be 0-9 or X.
        /// </summary>
        internal static string Modulus11AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus11AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus11.
        /// </summary>
        internal static string Modulus11AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus11AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus 11 algorithm where every character is weighted by its position, starting from the right-most character. Generated check digit will be 0-9. Values that result in a check value of 10 are rejected.
        /// </summary>
        internal static string Modulus11DecimalAlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus11DecimalAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus11Decimal.
        /// </summary>
        internal static string Modulus11DecimalAlgorithmName {
            get {
                return ResourceManager.GetString("Modulus11DecimalAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus must be &gt;= 2.
        /// </summary>
        internal static string ModulusIntModulusOutOfRangeMessage {
            get {
                return ResourceManager.GetString("ModulusIntModulusOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be &gt;= 0 and &lt; {0}.
        /// </summary>
        internal static string ModulusIntValueOutOfRangeMessageFormat {
            get {
                return ResourceManager.GetString("ModulusIntValueOutOfRangeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOID (Nice Opaque Identifier) check digit algorithm, betanumeric modulus 29.
        /// </summary>
        internal static string NcdAlgorithmDescription {
            get {
                return ResourceManager.GetString("NcdAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOID Check Digit.
        /// </summary>
        internal static string NcdAlgorithmName {
            get {
                return ResourceManager.GetString("NcdAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS - Modulus 11, but only with check digits of 0-9.
        /// </summary>
        internal static string NhsAlgorithmDescription {
            get {
                return ResourceManager.GetString("NhsAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS (UK National Health Service).
        /// </summary>
        internal static string NhsAlgorithmName {
            get {
                return ResourceManager.GetString("NhsAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPI - Luhn algorithm with constant &quot;80840&quot; prefix.
        /// </summary>
        internal static string NpiAlgorithmDescription {
            get {
                return ResourceManager.GetString("NpiAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPI (US National Provider Identifier).
        /// </summary>
        internal static string NpiAlgorithmName {
            get {
                return ResourceManager.GetString("NpiAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDOL Algorithm.
        /// </summary>
        internal static string SedolAlgorithmDescription {
            get {
                return ResourceManager.GetString("SedolAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDOL.
        /// </summary>
        internal static string SedolAlgorithmName {
            get {
                return ResourceManager.GetString("SedolAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verhoeff&apos;s dihedral algorithm.
        /// </summary>
        internal static string VerhoeffAlgorithmDescription {
            get {
                return ResourceManager.GetString("VerhoeffAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verhoeff.
        /// </summary>
        internal static string VerhoeffAlgorithmName {
            get {
                return ResourceManager.GetString("VerhoeffAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN Algorithm - weighted modulus 11 algorithm with transliteration of alphabetic characters.
        /// </summary>
        internal static string VinAlgorithmDescription {
            get {
                return ResourceManager.GetString("VinAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN (Vehicle Identification Number).
        /// </summary>
        internal static string VinAlgorithmName {
            get {
                return ResourceManager.GetString("VinAlgorithmName", resourceCulture);
            }
        }
    }
}
