//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDigits.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckDigits.Net.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Bankers Association Routing Transit Number algorithm with weights 3, 7 and 1.
        /// </summary>
        internal static string AbaRtnAlgorithmDescription {
            get {
                return ResourceManager.GetString("AbaRtnAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABA RTN.
        /// </summary>
        internal static string AbaRtnAlgorithmName {
            get {
                return ResourceManager.GetString("AbaRtnAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damm&apos;s quasigroup algorithm.
        /// </summary>
        internal static string DammAlgorithmDescription {
            get {
                return ResourceManager.GetString("DammAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damm.
        /// </summary>
        internal static string DammAlgorithmName {
            get {
                return ResourceManager.GetString("DammAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhn algorithm - modulus 10 algorithm with weight 2 applied to every odd position character.
        /// </summary>
        internal static string LuhnAlgorithmDescription {
            get {
                return ResourceManager.GetString("LuhnAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhn.
        /// </summary>
        internal static string LuhnAlgorithmName {
            get {
                return ResourceManager.GetString("LuhnAlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_13 - modulus 10 algorithm with weights 1 and 3.
        /// </summary>
        internal static string Modulus10_13AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus10_13AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus10_13.
        /// </summary>
        internal static string Modulus10_13AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus10_13AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus 11 algorithm where every character is weighted by its position, starting from the right-most character. Generated check digit will be 0-9 or X.
        /// </summary>
        internal static string Modulus11AlgorithmDescription {
            get {
                return ResourceManager.GetString("Modulus11AlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus11.
        /// </summary>
        internal static string Modulus11AlgorithmName {
            get {
                return ResourceManager.GetString("Modulus11AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verhoeff&apos;s dihedral algorithm.
        /// </summary>
        internal static string VerhoeffAlgorithmDescription {
            get {
                return ResourceManager.GetString("VerhoeffAlgorithmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verhoeff.
        /// </summary>
        internal static string VerhoeffAlgorithmName {
            get {
                return ResourceManager.GetString("VerhoeffAlgorithmName", resourceCulture);
            }
        }
    }
}
