@AnnotationsDemoApi_HostAddress = http://localhost:5079

### [LuhnCheckDigit] Valid Luhn Card Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/luhn
Content-Type: application/json

{
  "cardNumber": "4539148803436467"
}


### [LuhnCheckDigit] Invalid Luhn Card Number - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/luhn
Content-Type: application/json

{
  "cardNumber": "4539148803436460"
}

### [LuhnCheckDigit(ErrorMessage =...)] Valid Luhn Card Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/luhnmessage
Content-Type: application/json

{
  "cardNumber": "4539148803436467"
}


### [LuhnCheckDigit(ErrorMessage =...)] Invalid Luhn Card Number - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/luhnmessage
Content-Type: application/json

{
  "cardNumber": "4539148803436460"
}


### [LuhnCheckDigit(ErrorMessageResourceName =...)] Valid Luhn Card Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/luhnglobal
Content-Type: application/json
Accept-Language: es-ES

{
  "cardNumber": "4539148803436467"
}


### [LuhnCheckDigit(ErrorMessageResourceName =...)] Invalid Luhn Card Number - Should return 400 Bad Request and localized message
POST {{AnnotationsDemoApi_HostAddress}}/luhnglobal
Content-Type: application/json
Accept-Language: es-ES

{
  "cardNumber": "4539148803436460"
}
