//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationsDemoApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnnotationsDemoApi.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Aadhaar ID number.
        /// </summary>
        public static string InvalidAadhaarNumber {
            get {
                return ResourceManager.GetString("InvalidAadhaarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ARK Identifier.
        /// </summary>
        public static string InvalidArkIdentifier {
            get {
                return ResourceManager.GetString("InvalidArkIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number.
        /// </summary>
        public static string InvalidCardNumber {
            get {
                return ResourceManager.GetString("InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CAS Registry Number.
        /// </summary>
        public static string InvalidCasNumber {
            get {
                return ResourceManager.GetString("InvalidCasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Donation Identifier.
        /// </summary>
        public static string InvalidDonationIdentifier {
            get {
                return ResourceManager.GetString("InvalidDonationIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Global Release Identifier.
        /// </summary>
        public static string InvalidGlobalReleaseIdentifier {
            get {
                return ResourceManager.GetString("InvalidGlobalReleaseIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid International Maritime Organization (IMO) Number.
        /// </summary>
        public static string InvalidImoNumber {
            get {
                return ResourceManager.GetString("InvalidImoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISBN-10.
        /// </summary>
        public static string InvalidIsbn10 {
            get {
                return ResourceManager.GetString("InvalidIsbn10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Item Identifier.
        /// </summary>
        public static string InvalidItemIdentifier {
            get {
                return ResourceManager.GetString("InvalidItemIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Legal Entity Identifier.
        /// </summary>
        public static string InvalidLegalEntityIdentifier {
            get {
                return ResourceManager.GetString("InvalidLegalEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO 7064 MOD 1271-36 Identifier.
        /// </summary>
        public static string InvalidMod1271_36Identifier {
            get {
                return ResourceManager.GetString("InvalidMod1271_36Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO 7064 MOD 27,26 Identifier.
        /// </summary>
        public static string InvalidMod27_26Identifier {
            get {
                return ResourceManager.GetString("InvalidMod27_26Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO 7064 MOD 661-26 Identifier.
        /// </summary>
        public static string InvalidMod661_26Identifier {
            get {
                return ResourceManager.GetString("InvalidMod661_26Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISO 7064 MOD 97-10 Identifier.
        /// </summary>
        public static string InvalidMod97_10Identifier {
            get {
                return ResourceManager.GetString("InvalidMod97_10Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISNI (International Standard Name Identifier).
        /// </summary>
        public static string InvalidStandardNameIdentifier {
            get {
                return ResourceManager.GetString("InvalidStandardNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Submission Identifier.
        /// </summary>
        public static string InvalidSubmissionIdentifier {
            get {
                return ResourceManager.GetString("InvalidSubmissionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UPC Code.
        /// </summary>
        public static string InvalidUpcCode {
            get {
                return ResourceManager.GetString("InvalidUpcCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid request.
        /// </summary>
        public static string ValidRequest {
            get {
                return ResourceManager.GetString("ValidRequest", resourceCulture);
            }
        }
    }
}
