@AnnotationsDemoApi_HostAddress = http://localhost:5079

### [AlphanumericMod97_10CheckDigit] Valid Legal Entity Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710
Content-Type: application/json

{
  "legalEntityIdentifier": "10Bx939c5543TqA1144M999143X38"
}


### [AlphanumericMod97_10CheckDigit] Invalid Legal Entity Identifier - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710
Content-Type: application/json

{
  "legalEntityIdentifier": "SC74MC0LB1031234567890123456USD"
}

### [AlphanumericMod97_10CheckDigit(ErrorMessage =...)] Valid Legal Entity Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710message
Content-Type: application/json

{
  "legalEntityIdentifier": "10Bx939c5543TqA1144M999143X38"
}


### [AlphanumericMod97_10CheckDigit(ErrorMessage =...)] Invalid Legal Entity Identifier - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710message
Content-Type: application/json

{
  "legalEntityIdentifier": "SC74MC0LB1031234567890123456USD"
}


### [AlphanumericMod97_10CheckDigit(ErrorMessageResourceName =...)] Valid Legal Entity Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710global
Content-Type: application/json
Accept-Language: de-DE

{
  "legalEntityIdentifier": "10Bx939c5543TqA1144M999143X38"
}


### [AlphanumericMod97_10CheckDigit(ErrorMessageResourceName =...)] Invalid Legal Entity Identifier - Should return 400 Bad Request and localized message
POST {{AnnotationsDemoApi_HostAddress}}/alphanumericmod9710global
Content-Type: application/json
Accept-Language: de-DE

{
  "legalEntityIdentifier": "SC74MC0LB1031234567890123456USD"
}
