@AnnotationsDemoApi_HostAddress = http://localhost:5079

### [Iso7064Mod11_2CheckDigit] Valid ISO/IEC 7064 MOD 11-2 value - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112
Content-Type: application/json

{
  "standardNameIdentifier": "0000000114767411"
}


### [Iso7064Mod11_2CheckDigit] Invalid ISO/IEC 7064 MOD 11-2 value - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112
Content-Type: application/json

{
  "standardNameIdentifier": "000000012156438X"
}

### [Iso7064Mod11_2CheckDigit(ErrorMessage =...)] Valid ISO/IEC 7064 MOD 11-2 value - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112message
Content-Type: application/json

{
  "standardNameIdentifier": "0000000114767411"
}


### [Iso7064Mod11_2CheckDigit(ErrorMessage =...)] Invalid ISO/IEC 7064 MOD 11-2 value - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112message
Content-Type: application/json

{
  "standardNameIdentifier": "000000012156438X"
}


### [Iso7064Mod11_2CheckDigit(ErrorMessageResourceName =...)] Valid ISO/IEC 7064 MOD 11-2 value - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112global
Content-Type: application/json
Accept-Language: es-ES

{
  "standardNameIdentifier": "0000000114767411"
}


### [Iso7064Mod11_2CheckDigit(ErrorMessageResourceName =...)] Invalid ISO/IEC 7064 MOD 11-2 value - Should return 400 Bad Request and localized message
POST {{AnnotationsDemoApi_HostAddress}}/iso7064mod112global
Content-Type: application/json
Accept-Language: es-ES

{
  "standardNameIdentifier": "000000012156438X"
}
