@AnnotationsDemoApi_HostAddress = http://localhost:5079

### [Modulus10_2CheckDigit] Valid IMO Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/modulus102
Content-Type: application/json

{
   "imoNumber": "9074729"
}


### [Modulus10_2CheckDigit] Invalid IMO Number - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/modulus102
Content-Type: application/json

{
  "imoNumber": "1020569"
}

### [Modulus10_2CheckDigit(ErrorMessage =...)] Valid IMO Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/modulus102message
Content-Type: application/json

{
  "imoNumber": "9074729"
}


### [Modulus10_2CheckDigit(ErrorMessage =...)] Invalid IMO Number - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/modulus102message
Content-Type: application/json

{
  "imoNumber": "1020569"
}


### [Modulus10_2CheckDigit(ErrorMessageResourceName =...)] Valid IMO Number - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/modulus102global
Content-Type: application/json
Accept-Language: de-DE

{
  "imoNumber": "9074729"
}


### [Modulus10_2CheckDigit(ErrorMessageResourceName =...)] Invalid IMO Number - Should return 400 Bad Request and localized message
POST {{AnnotationsDemoApi_HostAddress}}/modulus102global
Content-Type: application/json
Accept-Language: de-DE

{
  "imoNumber": "1020569"
}
