@AnnotationsDemoApi_HostAddress = http://localhost:5079

### [NoidCheckDigit] Valid ARK Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/noid
Content-Type: application/json

{
  "arkIdentifier": "13030/xf93gt2q"
}


### [NoidCheckDigit] Invalid ARK Identifier - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/noid
Content-Type: application/json

{
  "arkIdentifier": "13030/tf5p30806k"
}

### [NoidCheckDigit(ErrorMessage =...)] Valid ARK Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/noidmessage
Content-Type: application/json

{
  "arkIdentifier": "13030/xf93gt2q"
}


### [NoidCheckDigit(ErrorMessage =...)] Invalid ARK Identifier - Should return 400 Bad Request
POST {{AnnotationsDemoApi_HostAddress}}/noidmessage
Content-Type: application/json

{
  "arkIdentifier": "13030/tf5p30806k"
}


### [NoidCheckDigit(ErrorMessageResourceName =...)] Valid ARK Identifier - Should return 200 OK
POST {{AnnotationsDemoApi_HostAddress}}/noidglobal
Content-Type: application/json
Accept-Language: de-DE

{
  "arkIdentifier": "13030/xf93gt2q"
}


### [NoidCheckDigit(ErrorMessageResourceName =...)] Invalid ARK Identifier - Should return 400 Bad Request and localized message
POST {{AnnotationsDemoApi_HostAddress}}/noidglobal
Content-Type: application/json
Accept-Language: de-DE

{
  "arkIdentifier": "13030/tf5p30806k"
}
